# Check NEORV32 software framework and test processor using cpu_test program

name: 'Processor Check'

on:
  push:
    branches:
    - master
    paths:
    - 'rtl/**'
    - 'sw/**'
    - 'sim/**'
  pull_request:
    branches:
    - master
    paths:
    - 'rtl/**'
    - 'sw/**'
    - 'sim/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: 'Processor Check'

    steps:

      - name: '🧰 Repository Checkout'
        uses: actions/checkout@v2

      - name: '🔧 Setup Environment Variables'
        run: |
          echo "$GITHUB_WORKSPACE/riscv/bin" >> $GITHUB_PATH
          echo $GITHUB_WORKSPACE

      - name: '🔧 Setup RISC-V GCC'
        run: |
          /bin/bash -c "chmod u+x ./.ci/install.sh && ./.ci/install.sh"
          echo $GITHUB_WORKSPACE

      - name: '🔧 Setup GHDL Simulator'
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: gcc

      - name: '⚙️ Run Software Framework Tests'
        run: /bin/bash -c "chmod u+x ./.ci/sw_check.sh && ./.ci/sw_check.sh"

      - name: '⚙️ Run Processor Hardware Tests'
        run: /bin/bash -c "chmod u+x ./.ci/hw_check.sh && ./.ci/hw_check.sh"
